import { Card } from './card';
import { Color } from './color';
import { CardSize } from './card-size';

export const CARDS: Card[] = [
    {
      id: 11,
      name: 'Eldritch Blast',
      borderColor: new Color('#444444'),
      tags: [ 'Evocation' ],
      cardSizeType: CardSize.Poker,
      // tslint:disable-next-line:max-line-length
      layoutText: 'title Eldritch Blast\nsubtitleEvocation cantrip\nattribute Casting Time | 1 Action\nattribute Duration | 1 Minute\ntext You use your action to create a beam of magical energy and hurl it at a creature you can see within range. Make a ranged spell attack. On hit, the target takes 1d10 force damage.\nheading At Higher Level\ntext The spell creates more beams as you level. At 5th, it makes two beams; at 11th, it makes three; and at 17th, it makes four. The beams can be directed at the same target or different ones. Each beam gets its own attack roll.\nability-scores 18 12 2 14 8 29',
    },
    {
      id: 12,
      name: 'Poker Card 1',
      borderColor: new Color('#444444'),
      tags: [],
      cardSizeType: CardSize.Poker,
      layoutText: 'title Poker Card 1',
    },
    {
      id: 13,
      name: 'Poker Card 2',
      borderColor: new Color('#444444'),
      tags: [],
      cardSizeType: CardSize.Poker,
      layoutText: 'title Poker Card 2',
    },
    {
      id: 14,
      name: 'Poker Card 3',
      borderColor: new Color('#444444'),
      tags: [],
      cardSizeType: CardSize.Poker,
      layoutText: 'title Poker Card 3',
    },
    {
      id: 15,
      name: 'Poker Card 4',
      borderColor: new Color('#444444'),
      tags: [],
      cardSizeType: CardSize.Poker,
      layoutText: 'title Poker Card 4',
    },
    {
      id: 16,
      name: 'Poker Card 5',
      borderColor: new Color('#444444'),
      tags: [],
      cardSizeType: CardSize.Poker,
      layoutText: 'title Poker Card 5',
    },
    {
      id: 17,
      name: 'Poker Card 6',
      borderColor: new Color('#444444'),
      tags: [],
      cardSizeType: CardSize.Poker,
      layoutText: 'title Poker Card 6',
    },
    {
      id: 18,
      name: 'Poker Card 7',
      borderColor: new Color('#444444'),
      tags: [],
      cardSizeType: CardSize.Poker,
      layoutText: 'title Poker Card 7',
    },
    {
      id: 19,
      name: 'Poker Card 8',
      borderColor: new Color('#444444'),
      tags: [],
      cardSizeType: CardSize.Poker,
      layoutText: 'title Poker Card 8',
    },
    {
      id: 20,
      name: 'Tarot Card 1',
      borderColor: new Color('#444444'),
      tags: [],
      cardSizeType: CardSize.Tarot,
      layoutText: 'title Tarot Card 1',
    },
    {
      id: 21,
      name: 'Tarot Card 2',
      borderColor: new Color('#444444'),
      tags: [],
      cardSizeType: CardSize.Tarot,
      layoutText: 'title Tarot Card 2',
    },
    {
      id: 22,
      name: 'Tarot Card 3',
      borderColor: new Color('#444444'),
      tags: [],
      cardSizeType: CardSize.Tarot,
      layoutText: 'title Tarot Card 3',
    },
    {
      id: 23,
      name: 'Tarot Card 4',
      borderColor: new Color('#444444'),
      tags: [],
      cardSizeType: CardSize.Tarot,
      layoutText: 'title Tarot Card 4',
    },
    {
      id: 24,
      name: 'Tarot Card 5',
      borderColor: new Color('#444444'),
      tags: [],
      cardSizeType: CardSize.Tarot,
      layoutText: 'title Tarot Card 5',
    },
    {
      id: 25,
      name: 'Tarot Card 6',
      borderColor: new Color('#444444'),
      tags: [],
      cardSizeType: CardSize.Tarot,
      layoutText: 'title Tarot Card 6',
    }
];
